[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F8FF"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 200

[browser]
gatherUsageStats = false
